//go:build nftables || all

package nftables

import (
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	itypes "github.com/joyautomation/tentacle/internal/types"
)

const (
	configDir     = "/etc/tentacle"
	configFile    = "nftables.json"
	rulesDir      = "/etc/nftables.d"
	rulesFile     = "60-tentacle-nat.conf"
	tableName     = "tentacle_nat"
)

// configPath returns the full path to the JSON config file.
func configPath() string { return filepath.Join(configDir, configFile) }

// rulesPath returns the full path to the generated nft rules file.
func rulesPath() string { return filepath.Join(rulesDir, rulesFile) }

// loadConfig reads the nftables JSON configuration from disk.
// If the file does not exist an empty config is returned.
func loadConfig() (*itypes.NftablesConfig, error) {
	data, err := os.ReadFile(configPath())
	if err != nil {
		if os.IsNotExist(err) {
			return &itypes.NftablesConfig{}, nil
		}
		return nil, fmt.Errorf("read config: %w", err)
	}
	var cfg itypes.NftablesConfig
	if err := json.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("parse config: %w", err)
	}
	return &cfg, nil
}

// saveConfig writes the nftables configuration to disk as JSON.
func saveConfig(log *slog.Logger, cfg *itypes.NftablesConfig) error {
	if err := os.MkdirAll(configDir, 0755); err != nil {
		return fmt.Errorf("create config dir: %w", err)
	}
	data, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal config: %w", err)
	}
	if err := os.WriteFile(configPath(), data, 0644); err != nil {
		return fmt.Errorf("write config: %w", err)
	}
	log.Info("nftables: config saved", "path", configPath(), "rules", len(cfg.NatRules))
	return nil
}

// generateRules produces an nft script that creates the tentacle_nat table
// with prerouting (DNAT) and postrouting (SNAT for doubleNat) chains.
func generateRules(rules []itypes.NatRule) string {
	var b strings.Builder

	b.WriteString("#!/usr/sbin/nft -f\n\n")
	b.WriteString(fmt.Sprintf("# Auto-generated by tentacle nftables module\n"))
	b.WriteString(fmt.Sprintf("# Rules: %d\n\n", len(rules)))

	// Flush any previous table (ignore errors if it doesn't exist).
	b.WriteString(fmt.Sprintf("table ip %s\n", tableName))
	b.WriteString(fmt.Sprintf("delete table ip %s\n\n", tableName))

	b.WriteString(fmt.Sprintf("table ip %s {\n", tableName))

	// ---- prerouting chain (DNAT) ----
	b.WriteString("  chain prerouting {\n")
	b.WriteString("    type nat hook prerouting priority dstnat; policy accept;\n")
	for _, r := range rules {
		if !r.Enabled {
			continue
		}
		line := preroutingLine(r)
		if line != "" {
			b.WriteString("    " + line + "\n")
		}
	}
	b.WriteString("  }\n\n")

	// ---- postrouting chain (SNAT for double-NAT) ----
	b.WriteString("  chain postrouting {\n")
	b.WriteString("    type nat hook postrouting priority srcnat; policy accept;\n")
	for _, r := range rules {
		if !r.Enabled || !r.DoubleNat {
			continue
		}
		line := postroutingLine(r)
		if line != "" {
			b.WriteString("    " + line + "\n")
		}
	}
	b.WriteString("  }\n")

	b.WriteString("}\n")
	return b.String()
}

// preroutingLine builds one DNAT rule.
func preroutingLine(r itypes.NatRule) string {
	var parts []string

	// Interface match.
	if r.IncomingInterface != "" {
		parts = append(parts, fmt.Sprintf("iifname \"%s\"", r.IncomingInterface))
	}

	// Protocol match.
	proto := strings.ToLower(r.Protocol)
	if proto != "" && proto != "all" {
		parts = append(parts, proto)
	}

	// Source restriction.
	if r.ConnectingDevices != "" && r.ConnectingDevices != "any" {
		parts = append(parts, fmt.Sprintf("ip saddr %s", r.ConnectingDevices))
	}

	// Destination address (the NAT address visible to the outside).
	if r.NatAddr != "" {
		parts = append(parts, fmt.Sprintf("ip daddr %s", r.NatAddr))
	}

	// Destination port.
	if r.OriginalPort != "" && proto != "" && proto != "all" && proto != "icmp" {
		parts = append(parts, fmt.Sprintf("dport %s", r.OriginalPort))
	}

	// Comment.
	if r.Comment != "" {
		parts = append(parts, fmt.Sprintf("comment \"%s\"", r.Comment))
	} else if r.DeviceName != "" {
		parts = append(parts, fmt.Sprintf("comment \"%s\"", r.DeviceName))
	}

	// DNAT target.
	dnatTarget := r.DeviceAddr
	if r.TranslatedPort != "" && proto != "" && proto != "all" && proto != "icmp" {
		dnatTarget = fmt.Sprintf("%s:%s", r.DeviceAddr, r.TranslatedPort)
	}
	parts = append(parts, fmt.Sprintf("dnat to %s", dnatTarget))

	return strings.Join(parts, " ")
}

// postroutingLine builds one SNAT rule for double-NAT scenarios.
func postroutingLine(r itypes.NatRule) string {
	var parts []string

	if r.OutgoingInterface != "" {
		parts = append(parts, fmt.Sprintf("oifname \"%s\"", r.OutgoingInterface))
	}

	parts = append(parts, fmt.Sprintf("ip daddr %s", r.DeviceAddr))

	snatAddr := r.DoubleNatAddr
	if snatAddr == "" {
		snatAddr = r.NatAddr
	}
	parts = append(parts, fmt.Sprintf("snat to %s", snatAddr))

	return strings.Join(parts, " ")
}

// writeRulesFile writes the generated nft script to the rules file on disk.
func writeRulesFile(content string) error {
	if err := os.MkdirAll(rulesDir, 0755); err != nil {
		return fmt.Errorf("create rules dir: %w", err)
	}
	if err := os.WriteFile(rulesPath(), []byte(content), 0644); err != nil {
		return fmt.Errorf("write rules file: %w", err)
	}
	return nil
}

// applyRules loads the generated rules file into the kernel via nft.
func applyRules(log *slog.Logger) error {
	cmd := exec.Command("nft", "-f", rulesPath())
	out, err := cmd.CombinedOutput()
	if err != nil {
		log.Error("nftables: failed to apply rules", "error", err, "output", string(out))
		return fmt.Errorf("nft -f: %s: %w", strings.TrimSpace(string(out)), err)
	}
	log.Info("nftables: rules applied successfully", "path", rulesPath())
	return nil
}

// getRuleset executes `nft -j list ruleset` and returns the raw JSON output.
func getRuleset(log *slog.Logger) (string, error) {
	cmd := exec.Command("nft", "-j", "list", "ruleset")
	out, err := cmd.CombinedOutput()
	if err != nil {
		log.Error("nftables: failed to list ruleset", "error", err, "output", string(out))
		return "", fmt.Errorf("nft list ruleset: %w", err)
	}
	return strings.TrimSpace(string(out)), nil
}
